2019-07-03 16:22:28,097 ERROR: Exception on /search [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 130, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2019-07-03 16:23:52,090 ERROR: Exception on /search [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 130, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2019-07-03 16:23:52,927 ERROR: Exception on /search [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 130, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2019-07-03 16:23:59,248 ERROR: Exception on /search [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 130, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2019-07-03 16:29:53,452 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-03 16:30:00,547 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-03 16:30:05,947 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-03 16:30:11,804 ERROR: Exception on /search [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 130, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2019-07-03 16:59:57,445 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-03 17:09:41,297 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-03 17:09:46,769 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-03 17:10:09,598 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-03 17:30:38,515 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-03 17:31:53,323 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-03 17:44:21,107 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
2019-07-03 17:44:29,420 ERROR: Exception on /search [GET] [in /home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/bahar/.virtualenvs/flaskenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/bahar/microblog/app/main/routes.py", line 129, in search
    if total > page * current_app.config['POSTS_PER_PAGE'] else None
TypeError: '>' not supported between instances of 'dict' and 'int'
2019-07-03 17:51:59,758 INFO: Microblog startup [in /home/bahar/microblog/app/__init__.py:76]
